name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: cmake .
      run: cmake .
    - name: cmake --build .
      run: cmake --build -j 8 .
